[package]
name = "conf-form"
version = "0.2.0"
authors = ["Daniele Tricoli <eriol@mornie.org>"]
license = "BSD-3"
readme = "README.md"

[dependencies]
clap = "2.32.0"
colored = "1.6.1"
indexmap = "1.0.2"
pest = "2.0"
pest_derive = "2.0"
serde = "1.0.80"
serde_yaml = "0.8.7"
